//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileComparisonMethod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PogingOmIetsTeVergelijken4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;741beab0-4411-45f9-ba43-ee8998a4be78&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;2&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:33:47.473+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://nictiz.nl/fhir/StructureDefinition/nl-core-observation&quot; /&gt;
        ///  &lt;name value=&quot;nl-core-observation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;Nictiz&quot; /&gt;
        ///  &lt;contact&gt;
        ///    &lt;name value=&quot;Nictiz&quot; /&gt;
        ///    &lt;telecom&gt;
        ///      &lt;system value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComparisonProfile {
            get {
                return ResourceManager.GetString("ComparisonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;024e4cc9-2eab-48b7-878e-aaaf59afd625&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;21&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-03T05:58:38.676+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;4&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;https://cscnextdev.atlassian.net/wiki/display/LAE/Extensions/CSC_HC_Observation_1&quot; /&gt;
        ///  &lt;name value=&quot;CSC_HC_Observation_1&quot; /&gt;
        ///  &lt;status value=&quot;draf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_1 {
            get {
                return ResourceManager.GetString("Profile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-PersonalValue&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:27.878+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-PersonalValue&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-PersonalValue&quot; /&gt;
        ///  &lt;display value=&quot;POWER2DM-PersonalValue&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;SRDC Corp.&quot; /&gt;
        ///  &lt;date value=&quot;2016-11-30T00:00:00+03:00&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_10 {
            get {
                return ResourceManager.GetString("Profile_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-PersonalValue&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;3&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-22T09:53:29.273+01:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM_PersonalValue&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM_PersonalValue&quot; /&gt;
        ///  &lt;display value=&quot;POWER2DM_PersonalValue&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;SRDC Corp.&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_11 {
            get {
                return ResourceManager.GetString("Profile_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-QuestionnaireResult&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:29.081+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-QuestionnaireResult&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-QuestionnaireResult&quot; /&gt;
        ///  &lt;display value=&quot;POWER2DM-QuestionnaireResult&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;SRDC Corp.&quot; /&gt;
        ///  &lt;date value=&quot;201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_12 {
            get {
                return ResourceManager.GetString("Profile_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-SimpleCodedObservation&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:29.784+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-SimpleCodedObservation&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-SimpleCodedObservation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;description value=&quot;StructureDefinition for POWER2DM-SimpleCodedObservationResource &quot; /&gt;
        ///  &lt;ki [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_13 {
            get {
                return ResourceManager.GetString("Profile_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-SimpleQuantityObservation&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:29.893+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-SimpleQuantityObservation&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-SimpleQuantityObservation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;description value=&quot;StructureDefinition for POWER2DM-SimpleQuantityObservationResource [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_14 {
            get {
                return ResourceManager.GetString("Profile_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-TimeSeriesObservation&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:30.3+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-TimeSeriesObservation&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-TimeSeriesObservation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;description value=&quot;StructureDefinition for POWER2DM-TimeSeriesObservation &quot; /&gt;
        ///  &lt;kind value=&quot;reso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_15 {
            get {
                return ResourceManager.GetString("Profile_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;PregnancyObservation&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2016-12-01T06:36:55.997+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;StructureDefinition/PregnancyObservation&quot; /&gt;
        ///  &lt;name value=&quot;PregnancyObservation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;fhirVersion value=&quot;1.0.2&quot; /&gt;
        ///  &lt;kind value=&quot;resource&quot; /&gt;
        ///  &lt;constrainedType value=&quot;Observation&quot; /&gt;
        ///  &lt;abstract value=&quot;false&quot; /&gt;
        ///  &lt;base value=&quot;http://hl7.org/fhir/StructureDefin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_16 {
            get {
                return ResourceManager.GetString("Profile_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;4d97253a-6613-49d5-8312-49601c26c3e7&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;3&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-02-05T14:43:46.856+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;StructureDefinition/4d97253a-6613-49d5-8312-49601c26c3e7&quot; /&gt;
        ///  &lt;name value=&quot;SimpleBodyWeight&quot; /&gt;
        ///  &lt;display value=&quot;Simple Body Weight&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2017-01-16T14:19:01.0259158+01:00&quot; /&gt;
        ///  &lt;kind value=&quot;resource&quot; /&gt;
        ///  &lt;constrainedType value=&quot;Obser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_17 {
            get {
                return ResourceManager.GetString("Profile_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;43d07819-cf46-4436-bce4-25f505cee4ce&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;3&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:34:31.162+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://nictiz.nl/fhir/StructureDefinition/Spirometer-Observation-FVC&quot; /&gt;
        ///  &lt;name value=&quot;Spirometer Observation FVC (L)&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2017-01-20T15:54:38.2660833+01:00&quot; /&gt;
        ///  &lt;fhirVersion value=&quot;1.0.2&quot; /&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_18 {
            get {
                return ResourceManager.GetString("Profile_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;774323d0-7263-4d72-85cd-feeb4ff92937&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:34:59.569+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://nictiz.nl/fhir/StructureDefinition/Spirometer-Observation-PEF&quot; /&gt;
        ///  &lt;name value=&quot;Spirometer Observation PEF&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2017-01-20T15:54:38.2660833+01:00&quot; /&gt;
        ///  &lt;fhirVersion value=&quot;1.0.2&quot; /&gt;
        ///  &lt;kind value=&quot;resource&quot; /&gt;
        ///  &lt;cons [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_19 {
            get {
                return ResourceManager.GetString("Profile_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;44fd14ca-fc0f-4318-92d9-a3ce9ef02fea&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;10&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-07T12:03:06.335+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://phr.kanta.fi/StructureDefinition/fiphr-bloodglucose&quot; /&gt;
        ///  &lt;version value=&quot;0.03&quot; /&gt;
        ///  &lt;name value=&quot;Finnish PHR Blood Glucose profile&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;experimental value=&quot;true&quot; /&gt;
        ///  &lt;date value=&quot;2017-02-08T14:17:44.456466+02:00&quot; /&gt;
        ///  &lt;description value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_2 {
            get {
                return ResourceManager.GetString("Profile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;1c9b3487-128d-43ea-bbf4-f05db92fa9f9&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;3&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:35:12.58+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://nictiz.nl/fhir/StructureDefinition/Spirometer-Observation-VCIN&quot; /&gt;
        ///  &lt;name value=&quot;Spirometer Observation VC IN&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2017-01-20T15:54:38.2660833+01:00&quot; /&gt;
        ///  &lt;fhirVersion value=&quot;1.0.2&quot; /&gt;
        ///  &lt;ki [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_20 {
            get {
                return ResourceManager.GetString("Profile_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;0b8abdc3-15c2-493d-a85a-b9900c43e0eb&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2016-11-18T13:53:03.509+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;StructureDefinition/TumorFinding&quot; /&gt;
        ///  &lt;name value=&quot;TumorFinding&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;fhirVersion value=&quot;1.0.2&quot; /&gt;
        ///  &lt;kind value=&quot;resource&quot; /&gt;
        ///  &lt;constrainedType value=&quot;Observation&quot; /&gt;
        ///  &lt;abstract value=&quot;false&quot; /&gt;
        ///  &lt;base value=&quot;http://hl7.org/fhir/StructureDefin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_21 {
            get {
                return ResourceManager.GetString("Profile_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;088679af-b106-42d7-a320-052652e800e2&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:41:52.74+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;additional&quot; /&gt;&lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;FunctioneleOfMentaleStatus as defined by the Dutch Clinical Building Block (Dutch: Zorginformatiebouwsteen or ZIB) version 3.0. The functional or mental status provid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_22 {
            get {
                return ResourceManager.GetString("Profile_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;a04df0e3-cd49-4cb2-84e8-ac147f692e93&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;7&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:42:11.237+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Observation&quot; /&gt;
        ///  &lt;name value=&quot;ZIB LaboratoryTestResult Observation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;Nictiz&quot; /&gt;
        ///  &lt;contact&gt;
        ///    &lt;name value=&quot;Nictiz&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_23 {
            get {
                return ResourceManager.GetString("Profile_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;28f2e632-8290-42e4-aac7-470a6f28ae92&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-04-05T13:43:24.605+02:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;additional&quot; /&gt;&lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;TabakGebruik as defined by the Dutch Clinical Building Block (Dutch: Zorginformatiebouwsteen or ZIB) version 3.0. Tobacco is a product that comes from the leaves of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_24 {
            get {
                return ResourceManager.GetString("Profile_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;fd39311f-c642-40da-985d-1160add4dbac&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;8&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-07T11:55:33.176+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://phr.kanta.fi/StructureDefinition/fiphr-bodyheight&quot; /&gt;
        ///  &lt;version value=&quot;0.03&quot; /&gt;
        ///  &lt;name value=&quot;Finnish PHR Body Height profile&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;experimental value=&quot;true&quot; /&gt;
        ///  &lt;date value=&quot;2017-02-07T14:04:16.7862783+02:00&quot; /&gt;
        ///  &lt;description value=&quot;Finn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_3 {
            get {
                return ResourceManager.GetString("Profile_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;3412d8d3-63f7-4cef-a3a6-9b59a44d8812&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;10&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-07T12:05:51.968+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://phr.kanta.fi/StructureDefinition/fiphr-heartrate&quot; /&gt;
        ///  &lt;version value=&quot;0.03&quot; /&gt;
        ///  &lt;name value=&quot;Finnish PHR Heart Rate profile&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;experimental value=&quot;true&quot; /&gt;
        ///  &lt;date value=&quot;2017-02-07T16:38:08.369396+02:00&quot; /&gt;
        ///  &lt;description value=&quot;Finnis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_4 {
            get {
                return ResourceManager.GetString("Profile_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml-model href=&quot;../../../../Documents/FHIR/Schemas/structuredefinition.sch&quot; type=&quot;application/xml&quot; schematypens=&quot;http://purl.oclc.org/dsdl/schematron&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;12cea424-6d80-45e0-a1d0-5738cf761438&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;2&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-07T12:02:38.623+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://phr.kanta.fi/StructureDefinition/fiphr-bodytemperature&quot; /&gt;
        ///  &lt;version value=&quot;0.03&quot; /&gt;
        ///  &lt;name value=&quot;Finnish PHR Tempe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_5 {
            get {
                return ResourceManager.GetString("Profile_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;MyObservation&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;4&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-21T17:27:09.122+01:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;4&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;StructureDefinition/LeukocytesLabTestObservation&quot; /&gt;
        ///  &lt;name value=&quot;LeukocytesLabTestObservation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_6 {
            get {
                return ResourceManager.GetString("Profile_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-MindState&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:27.268+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-MindState&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-MindState&quot; /&gt;
        ///  &lt;display value=&quot;POWER2DM-MindState&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;SRDC Corp.&quot; /&gt;
        ///  &lt;date value=&quot;2016-11-30T00:00:00+03:00&quot; /&gt;
        ///  &lt;descripti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_7 {
            get {
                return ResourceManager.GetString("Profile_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;94290bdf-d682-4883-aa98-7e5309226e95&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2016-10-04T18:00:43.901+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.medinformatix.com/fhir/resources/Observation&quot; /&gt;
        ///  &lt;name value=&quot;Observation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;MedInformatix&quot; /&gt;
        ///  &lt;contact&gt;
        ///    &lt;name value=&quot;Dale Trinh&quot; /&gt;
        ///    &lt;telecom&gt;
        ///      &lt;system value=&quot;phone&quot; /&gt;
        ///      &lt;value value=&quot;3103487367 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_8 {
            get {
                return ResourceManager.GetString("Profile_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;POWER2DM-Observation&quot; /&gt;
        ///  &lt;meta&gt;
        ///    &lt;versionId value=&quot;1&quot; /&gt;
        ///    &lt;lastUpdated value=&quot;2017-03-14T11:39:27.503+00:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://www.power2dm.eu/pds/StructureDefinition/POWER2DM-Observation&quot; /&gt;
        ///  &lt;version value=&quot;0.1&quot; /&gt;
        ///  &lt;name value=&quot;POWER2DM-Observation&quot; /&gt;
        ///  &lt;display value=&quot;POWER2DM-Observation&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;SRDC Corp.&quot; /&gt;
        ///  &lt;date value=&quot;2016-11-30T00:00:00+03:00&quot; /&gt;
        ///  &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile_9 {
            get {
                return ResourceManager.GetString("Profile_9", resourceCulture);
            }
        }
    }
}
